package pojo;
// Generated 25/09/2013 22:35:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Concepto generated by hbm2java
 */
public class Concepto  implements java.io.Serializable {


     private int codCon;
     private String descripcion;
     private boolean cargaUsuario;
     private boolean tipo;
     private Set<Novedad> novedads = new HashSet<Novedad>(0);

    public Concepto() {
    }

	
    public Concepto(int codCon, String descripcion, boolean cargaUsuario, boolean tipo) {
        this.codCon = codCon;
        this.descripcion = descripcion;
        this.cargaUsuario = cargaUsuario;
        this.tipo = tipo;
    }
    public Concepto(int codCon, String descripcion, boolean cargaUsuario, boolean tipo, Set<Novedad> novedads) {
       this.codCon = codCon;
       this.descripcion = descripcion;
       this.cargaUsuario = cargaUsuario;
       this.tipo = tipo;
       this.novedads = novedads;
    }
   
    public int getCodCon() {
        return this.codCon;
    }
    
    public void setCodCon(int codCon) {
        this.codCon = codCon;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isCargaUsuario() {
        return this.cargaUsuario;
    }
    
    public void setCargaUsuario(boolean cargaUsuario) {
        this.cargaUsuario = cargaUsuario;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public Set<Novedad> getNovedads() {
        return this.novedads;
    }
    
    public void setNovedads(Set<Novedad> novedads) {
        this.novedads = novedads;
    }




}


