package pojo;
// Generated 30/08/2013 08:52:29 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer legajo;
     private Sucursal sucursal;
     private Empresa empresa;
     private String apellido;
     private String nombre;
     private String cuit;
     private String convenio;
     private String tarea;
     private Set usuarios = new HashSet(0);
     private Set novedads = new HashSet(0);
     private Set sucursals = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Sucursal sucursal, Empresa empresa, String apellido, String nombre, String cuit, String convenio, String tarea) {
        this.sucursal = sucursal;
        this.empresa = empresa;
        this.apellido = apellido;
        this.nombre = nombre;
        this.cuit = cuit;
        this.convenio = convenio;
        this.tarea = tarea;
    }
    public Empleado(Sucursal sucursal, Empresa empresa, String apellido, String nombre, String cuit, String convenio, String tarea, Set usuarios, Set novedads, Set sucursals) {
       this.sucursal = sucursal;
       this.empresa = empresa;
       this.apellido = apellido;
       this.nombre = nombre;
       this.cuit = cuit;
       this.convenio = convenio;
       this.tarea = tarea;
       this.usuarios = usuarios;
       this.novedads = novedads;
       this.sucursals = sucursals;
    }
   
    public Integer getLegajo() {
        return this.legajo;
    }
    
    public void setLegajo(Integer legajo) {
        this.legajo = legajo;
    }
    public Sucursal getSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(Sucursal sucursal) {
        this.sucursal = sucursal;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getConvenio() {
        return this.convenio;
    }
    
    public void setConvenio(String convenio) {
        this.convenio = convenio;
    }
    public String getTarea() {
        return this.tarea;
    }
    
    public void setTarea(String tarea) {
        this.tarea = tarea;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getNovedads() {
        return this.novedads;
    }
    
    public void setNovedads(Set novedads) {
        this.novedads = novedads;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }




}


