package pojo;
// Generated 03/09/2013 17:08:28 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer codEmp;
     private String nombre;
     private String gerente;
     private String mailGerente;
     private Set sucursals = new HashSet(0);
     private Set empleadoses = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String gerente, String mailGerente) {
        this.gerente = gerente;
        this.mailGerente = mailGerente;
    }
    public Empresa(String nombre, String gerente, String mailGerente, Set sucursals, Set empleadoses) {
       this.nombre = nombre;
       this.gerente = gerente;
       this.mailGerente = mailGerente;
       this.sucursals = sucursals;
       this.empleadoses = empleadoses;
    }
   
    public Integer getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(Integer codEmp) {
        this.codEmp = codEmp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGerente() {
        return this.gerente;
    }
    
    public void setGerente(String gerente) {
        this.gerente = gerente;
    }
    public String getMailGerente() {
        return this.mailGerente;
    }
    
    public void setMailGerente(String mailGerente) {
        this.mailGerente = mailGerente;
    }
    public Set getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set sucursals) {
        this.sucursals = sucursals;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


