package pojo;
// Generated 25/09/2013 22:35:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer codEmp;
     private String nombre;
     private String gerente;
     private String mailGerente;
     private Set<Sucursal> sucursals = new HashSet<Sucursal>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Empresa() {
    }

	
    public Empresa(String gerente, String mailGerente) {
        this.gerente = gerente;
        this.mailGerente = mailGerente;
    }
    public Empresa(String nombre, String gerente, String mailGerente, Set<Sucursal> sucursals, Set<Empleado> empleados) {
       this.nombre = nombre;
       this.gerente = gerente;
       this.mailGerente = mailGerente;
       this.sucursals = sucursals;
       this.empleados = empleados;
    }
   
    public Integer getCodEmp() {
        return this.codEmp;
    }
    
    public void setCodEmp(Integer codEmp) {
        this.codEmp = codEmp;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGerente() {
        return this.gerente;
    }
    
    public void setGerente(String gerente) {
        this.gerente = gerente;
    }
    public String getMailGerente() {
        return this.mailGerente;
    }
    
    public void setMailGerente(String mailGerente) {
        this.mailGerente = mailGerente;
    }
    public Set<Sucursal> getSucursals() {
        return this.sucursals;
    }
    
    public void setSucursals(Set<Sucursal> sucursals) {
        this.sucursals = sucursals;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


