package pojo;
// Generated 17/09/2013 21:47:20 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sucursal generated by hbm2java
 */
public class Sucursal  implements java.io.Serializable {


     private int codSuc;
     private Empleado empleados;
     private Empresa empresa;
     private String nombre;
     private Set<Empleado> empleadoses = new HashSet<Empleado>(0);

    public Sucursal() {
    }

	
    public Sucursal(int codSuc, Empleado empleados, Empresa empresa, String nombre) {
        this.codSuc = codSuc;
        this.empleados = empleados;
        this.empresa = empresa;
        this.nombre = nombre;
    }
    public Sucursal(int codSuc, Empleado empleados, Empresa empresa, String nombre, Set<Empleado> empleadoses) {
       this.codSuc = codSuc;
       this.empleados = empleados;
       this.empresa = empresa;
       this.nombre = nombre;
       this.empleadoses = empleadoses;
    }
   
    public int getCodSuc() {
        return this.codSuc;
    }
    
    public void setCodSuc(int codSuc) {
        this.codSuc = codSuc;
    }
    public Empleado getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleado empleados) {
        this.empleados = empleados;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleado> getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set<Empleado> empleadoses) {
        this.empleadoses = empleadoses;
    }




}


