package co.tecnomati.java.controlcaja.dominio;
// Generated 06/10/2013 01:19:46 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriacomprobante generated by hbm2java
 */
public class Categoriacomprobante  implements java.io.Serializable {


     private Integer codigoCategoria;
     private String descripcion;
     private Set<Tipocomprobante> tipocomprobantes = new HashSet<Tipocomprobante>(0);

    public Categoriacomprobante() {
    }

    public Categoriacomprobante(String descripcion, Set<Tipocomprobante> tipocomprobantes) {
       this.descripcion = descripcion;
       this.tipocomprobantes = tipocomprobantes;
    }
   
    public Integer getCodigoCategoria() {
        return this.codigoCategoria;
    }
    
    public void setCodigoCategoria(Integer codigoCategoria) {
        this.codigoCategoria = codigoCategoria;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Tipocomprobante> getTipocomprobantes() {
        return this.tipocomprobantes;
    }
    
    public void setTipocomprobantes(Set<Tipocomprobante> tipocomprobantes) {
        this.tipocomprobantes = tipocomprobantes;
    }




}


