package co.tecnomati.java.controlcaja.dominio;
// Generated 23/09/2013 20:39:06 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private Integer id;
     private Tipocomprobante tipocomprobante;
     private long numeroSerie; // numero de recibo
     private int idEntidad;  // identificador de la persona autoincremental
     private Integer tipoPersona; //0 asociado 1proveedor o 2cliente
     private Date fecha;  // de emision de recibo
     private Integer tipoProceso; //0 entrada o 1 salida
     private Date ejercicioEconomico;  // que es un dato de un recibo 
     private Set<Comprobanteconcepto> comprobanteconceptos = new HashSet<Comprobanteconcepto>(0); // conjunto de conceptos(detalle) que tiene el recibo

    public Comprobante() {
    }

	
    public Comprobante(long numeroSerie, int idEntidad) {
        this.numeroSerie = numeroSerie;
        this.idEntidad = idEntidad;
    }
    public Comprobante(Tipocomprobante tipocomprobante, long numeroSerie, int idEntidad, Integer tipoPersona, Date fecha, Integer tipoProceso, Date ejercicioEconomico, Set<Comprobanteconcepto> comprobanteconceptos) {
       this.tipocomprobante = tipocomprobante;
       this.numeroSerie = numeroSerie;
       this.idEntidad = idEntidad;
       this.tipoPersona = tipoPersona;
       this.fecha = fecha;
       this.tipoProceso = tipoProceso;
       this.ejercicioEconomico = ejercicioEconomico;
       this.comprobanteconceptos = comprobanteconceptos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipocomprobante getTipocomprobante() {
        return this.tipocomprobante;
    }
    
    public void setTipocomprobante(Tipocomprobante tipocomprobante) {
        this.tipocomprobante = tipocomprobante;
    }
    public long getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(long numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public int getIdEntidad() {
        return this.idEntidad;
    }
    
    public void setIdEntidad(int idEntidad) {
        this.idEntidad = idEntidad;
    }
    public Integer getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(Integer tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getTipoProceso() {
        return this.tipoProceso;
    }
    
    public void setTipoProceso(Integer tipoProceso) {
        this.tipoProceso = tipoProceso;
    }
    public Date getEjercicioEconomico() {
        return this.ejercicioEconomico;
    }
    
    public void setEjercicioEconomico(Date ejercicioEconomico) {
        this.ejercicioEconomico = ejercicioEconomico;
    }
    public Set<Comprobanteconcepto> getComprobanteconceptos() {
        return this.comprobanteconceptos;
    }
    
    public void setComprobanteconceptos(Set<Comprobanteconcepto> comprobanteconceptos) {
        this.comprobanteconceptos = comprobanteconceptos;
    }




}


