package co.tecnomati.java.controlcaja.dominio;
// Generated 23/09/2013 14:41:58 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprobante generated by hbm2java
 */
public class Comprobante  implements java.io.Serializable {


     private Integer id;
     private Tipocomprobante tipocomprobante;
     private long numeroSerie;
     private Long cuit;
     private Integer tipoPersona;
     private Date fecha;
     private Integer tipoProceso;
     private Date ejercicioEconomico;
     private Set<Comprobanteconcepto> comprobanteconceptos = new HashSet<Comprobanteconcepto>(0);

    public Comprobante() {
    }

	
    public Comprobante(long numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Comprobante(Tipocomprobante tipocomprobante, long numeroSerie, Long cuit, Integer tipoPersona, Date fecha, Integer tipoProceso, Date ejercicioEconomico, Set<Comprobanteconcepto> comprobanteconceptos) {
       this.tipocomprobante = tipocomprobante;
       this.numeroSerie = numeroSerie;
       this.cuit = cuit;
       this.tipoPersona = tipoPersona;
       this.fecha = fecha;
       this.tipoProceso = tipoProceso;
       this.ejercicioEconomico = ejercicioEconomico;
       this.comprobanteconceptos = comprobanteconceptos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tipocomprobante getTipocomprobante() {
        return this.tipocomprobante;
    }
    
    public void setTipocomprobante(Tipocomprobante tipocomprobante) {
        this.tipocomprobante = tipocomprobante;
    }
    public long getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(long numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Long getCuit() {
        return this.cuit;
    }
    
    public void setCuit(Long cuit) {
        this.cuit = cuit;
    }
    public Integer getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(Integer tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getTipoProceso() {
        return this.tipoProceso;
    }
    
    public void setTipoProceso(Integer tipoProceso) {
        this.tipoProceso = tipoProceso;
    }
    public Date getEjercicioEconomico() {
        return this.ejercicioEconomico;
    }
    
    public void setEjercicioEconomico(Date ejercicioEconomico) {
        this.ejercicioEconomico = ejercicioEconomico;
    }
    public Set<Comprobanteconcepto> getComprobanteconceptos() {
        return this.comprobanteconceptos;
    }
    
    public void setComprobanteconceptos(Set<Comprobanteconcepto> comprobanteconceptos) {
        this.comprobanteconceptos = comprobanteconceptos;
    }




}


