package co.tecnomati.java.controlcaja.dominio;
// Generated 10/09/2013 18:55:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cooperativa generated by hbm2java
 */
public class Cooperativa  implements java.io.Serializable {


     private int matricula;
     private Integer cuit;
     private String nombre;
     private Date fechaIngreso;
     private String telefono;
     private String domicilio;
     private Set<Asociado> asociados = new HashSet<Asociado>(0);

    public Cooperativa() {
    }

	
    public Cooperativa(int matricula) {
        this.matricula = matricula;
    }
    public Cooperativa(int matricula, Integer cuit, String nombre, Date fechaIngreso, String telefono, String domicilio, Set<Asociado> asociados) {
       this.matricula = matricula;
       this.cuit = cuit;
       this.nombre = nombre;
       this.fechaIngreso = fechaIngreso;
       this.telefono = telefono;
       this.domicilio = domicilio;
       this.asociados = asociados;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public Integer getCuit() {
        return this.cuit;
    }
    
    public void setCuit(Integer cuit) {
        this.cuit = cuit;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public Set<Asociado> getAsociados() {
        return this.asociados;
    }
    
    public void setAsociados(Set<Asociado> asociados) {
        this.asociados = asociados;
    }




}


