package co.tecnomati.java.controlcaja.dominio;
// Generated 21/08/2013 18:13:09 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoFormulario generated by hbm2java
 */
public class TipoFormulario  implements java.io.Serializable {


     private Integer codigo;
     private String formulario;
     private String atajo;
     private Set<Formulario> formularios = new HashSet<Formulario>(0);

    public TipoFormulario() {
    }

    public TipoFormulario(String formulario, String atajo, Set<Formulario> formularios) {
       this.formulario = formulario;
       this.atajo = atajo;
       this.formularios = formularios;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }
    public String getAtajo() {
        return this.atajo;
    }
    
    public void setAtajo(String atajo) {
        this.atajo = atajo;
    }
    public Set<Formulario> getFormularios() {
        return this.formularios;
    }
    
    public void setFormularios(Set<Formulario> formularios) {
        this.formularios = formularios;
    }




}


