package co.tecnomati.java.controlcaja.dominio;
// Generated 09/08/2013 15:08:02 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoFormulario generated by hbm2java
 */
public class TipoFormulario  implements java.io.Serializable {


     private int codigo;
     private String formulario;
     private String tipo;
     private String accion;
     private Set<Formulario> formularios = new HashSet<Formulario>(0);

    public TipoFormulario() {
    }

	
    public TipoFormulario(int codigo) {
        this.codigo = codigo;
    }
    public TipoFormulario(int codigo, String formulario, String tipo, String accion, Set<Formulario> formularios) {
       this.codigo = codigo;
       this.formulario = formulario;
       this.tipo = tipo;
       this.accion = accion;
       this.formularios = formularios;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getFormulario() {
        return this.formulario;
    }
    
    public void setFormulario(String formulario) {
        this.formulario = formulario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Set<Formulario> getFormularios() {
        return this.formularios;
    }
    
    public void setFormularios(Set<Formulario> formularios) {
        this.formularios = formularios;
    }




}


